name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: restart server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ericontiveros.com
          username: root
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/portfolio
            git pull
            npm install
            pm2 restart 0
